import { AppSidebar } from '@/components/blocks/nav/app-sidebar';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import type { Metadata } from 'next';
import { Geist, Geist_Mono, Space_Grotesk } from 'next/font/google';
import './globals.css';

import AppBread from '@/components/blocks/nav/app-bread';
import { Separator } from '@/components/ui/separator';
import { Button } from '@/components/ui/button';
import { Globe2 } from 'lucide-react';
import LanguagePicker from '@/components/blocks/nav/language-picker';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const spaceGrotesk = Space_Grotesk({
  variable: '--font-space-grotesk',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${spaceGrotesk.variable} antialiased **:font-mono`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="flex max-h-screen flex-1 flex-col">
            <div className="bg-sidebar border-sidebar-border flex h-full max-h-[48.4px] w-full items-center justify-between border-b p-2">
              <div className="flex items-center gap-2">
                <SidebarTrigger className="size-8 cursor-pointer" />
                <Separator orientation="vertical" className="mr-2 h-4!" />
                <AppBread />
              </div>

              <div className="flex items-center gap-2 *:cursor-pointer">
                <LanguagePicker />
              </div>
            </div>
            <section className="relative flex flex-1 overflow-hidden shadow-[inset_0_0_10px_0] shadow-black/10">
              {children}
            </section>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
